//TODO: REMOVE THIS FILE! this is only mock data to test the frontend.

export const aScenarios = [
  {
    id: 1,
    title: '1 A',
    description: 'Providing information on a passage through a strait',
    icon: '',
    difficulty: 'beginner',
    objectives: [],
    initialMessage: 'You are approaching the Gibraltar Strait aboard MV OCEAN NAVIGATOR. Contact VTS to provide information about your passage through the strait.',
    expectedProtocol: ['call VTS', 'vessel identification', 'current position', 'intended route', 'ETA'],
  },
  {
    id: 2,
    title: '2 A',
    description: 'Providing and reading back anchoring position coordinates',
    icon: '',
    difficulty: 'beginner',
    objectives: [],
    initialMessage: "VTS has assigned you an anchorage position at 51°23.5'N 003°15.2'E. Read back the coordinates to confirm.",
    expectedProtocol: ['acknowledge', 'read back coordinates', 'confirm position', 'request clarification if needed'],
  },
  {
    id: 3,
    title: '3 A',
    description: 'Vessel enters VTS area and must drop anchor to wait for pilot',
    icon: '',
    difficulty: 'intermediate',
    objectives: [],
    initialMessage: 'You are aboard MV BALTIC STAR entering Rotterdam VTS area. You need to anchor and wait for a pilot. Contact VTS.',
    expectedProtocol: ['call VTS', 'vessel identification', 'position', 'request anchorage', 'pilot ETA'],
  },
  {
    id: 4,
    title: '4 A',
    description: 'Vessel ready to departure calls to ask clearance',
    icon: '',
    difficulty: 'beginner',
    objectives: [],
    initialMessage: 'MV CONTINENTAL is ready to depart from Berth 12. All lines are singled up. Contact VTS for departure clearance.',
    expectedProtocol: ['call VTS', 'vessel identification', 'berth position', 'ready to depart', 'request clearance'],
  },
  {
    id: 5,
    title: '5 A',
    description: 'Entering the reporting zone',
    icon: '',
    difficulty: 'beginner',
    objectives: [],
    initialMessage: 'You are entering the Dover Strait reporting zone aboard MV ATLANTIC PRIDE. Make your initial report to Dover Coastguard.',
    expectedProtocol: ['call station', 'vessel identification', 'position', 'course and speed', 'destination'],
  },
  {
    id: 6,
    title: '6 A',
    description: 'Vessel in transit to pilot station',
    icon: '',
    difficulty: 'beginner',
    objectives: [],
    initialMessage: 'MV NORDIC BREEZE is proceeding to Pilot Station Alpha. Your ETA is 30 minutes. Contact VTS with your status.',
    expectedProtocol: ['call VTS', 'vessel identification', 'in transit to pilot station', 'ETA', 'request confirmation'],
  },
  {
    id: 7,
    title: '7 A',
    description: 'Traffic information on permission to drift',
    icon: '',
    difficulty: 'intermediate',
    objectives: [],
    initialMessage: "You need to carry out engine repairs aboard MV SEA GUARDIAN at position 52°15'N 004°30'E. Request permission from VTS to drift.",
    expectedProtocol: ['call VTS', 'vessel identification', 'position', 'reason for drifting', 'request permission'],
  },
  {
    id: 8,
    title: '8 A',
    description: 'Tugboat outbound to escort incoming vessel to berth',
    icon: '',
    difficulty: 'intermediate',
    objectives: [],
    initialMessage: 'You are the master of tugboat POWERFUL. VTS has assigned you to escort MV EUROPA to Berth 15. Contact the incoming vessel.',
    expectedProtocol: ['call vessel', 'tugboat identification', 'confirm assignment', 'coordinate meeting point', 'confirm operations'],
  },
  {
    id: 9,
    title: '9 A',
    description: 'Vessel entering VTS area, in transit',
    icon: '',
    difficulty: 'beginner',
    objectives: [],
    initialMessage: 'MV STAR OF ASIA is entering Singapore VTS area, bound for Jurong Port. Contact VTS with your particulars.',
    expectedProtocol: ['call VTS', 'vessel identification', 'position', 'destination', 'ETA'],
  },
  {
    id: 10,
    title: '10 A',
    description: 'Leaving the TSS',
    icon: '',
    difficulty: 'beginner',
    objectives: [],
    initialMessage: 'You are leaving the English Channel TSS aboard MV MERCHANT QUEEN. Report to Channel Navigation.',
    expectedProtocol: ['call station', 'vessel identification', 'position', 'leaving TSS', 'next route'],
  },
  {
    id: 11,
    title: '11 A',
    description: 'Vessel underway with pilot onboard',
    icon: '',
    difficulty: 'beginner',
    objectives: [],
    initialMessage: 'MV EASTERN GLORY has pilot onboard and is proceeding to Berth 8. Contact VTS with your status.',
    expectedProtocol: ['call VTS', 'vessel identification', 'pilot onboard', 'destination berth', 'ETA'],
  },
  {
    id: 12,
    title: '12 A',
    description: 'Vessel entering VTS area bound for berth place and asking for information',
    icon: '',
    difficulty: 'beginner',
    objectives: [],
    initialMessage: 'MV PACIFIC CARRIER is entering Hamburg VTS area, bound for Container Terminal. Request berth availability and approach information.',
    expectedProtocol: ['call VTS', 'vessel identification', 'destination', 'request berth information', 'confirm instructions'],
  },
  {
    id: 13,
    title: '13 A',
    description: 'Mandatory ship reporting',
    icon: '',
    difficulty: 'beginner',
    objectives: [],
    initialMessage: 'You must complete mandatory reporting to Port Control for MV GLOBAL TRADER. Provide all required information.',
    expectedProtocol: ['call port control', 'vessel identification', 'position', 'last port', 'next port', 'cargo details'],
  },
  {
    id: 14,
    title: '14 A',
    description: 'Tug operations with barge in tow',
    icon: '',
    difficulty: 'intermediate',
    objectives: [],
    initialMessage: 'Tugboat HERCULES with barge CARGO-1 in tow is entering the harbor approach. Contact VTS with your configuration and intentions.',
    expectedProtocol: ['call VTS', 'tug identification', 'barge details', 'tow configuration', 'destination'],
  },
  {
    id: 15,
    title: '15 A',
    description: 'VTS grants the ship permission to enter the bay',
    icon: '',
    difficulty: 'beginner',
    objectives: [],
    initialMessage: 'VTS has granted MV COASTAL TRADER permission to enter Tokyo Bay. Acknowledge and confirm your intentions.',
    expectedProtocol: ['acknowledge permission', 'confirm vessel name', 'confirm route', 'maintain VHF watch'],
  },
  {
    id: 16,
    title: '16 A',
    description: 'Traffic and anchoring information',
    icon: '',
    difficulty: 'intermediate',
    objectives: [],
    initialMessage: 'MV NORTHERN WAVE needs to anchor due to weather conditions. Request traffic and anchoring information from VTS.',
    expectedProtocol: ['call VTS', 'vessel identification', 'request traffic information', 'request anchorage', 'confirm instructions'],
  },
  {
    id: 17,
    title: '17 A',
    description: 'Is the vessel AIS operational?',
    icon: '',
    difficulty: 'beginner',
    objectives: [],
    initialMessage: 'VTS is asking MV MARINE EXPLORER if your AIS is operational. They cannot see you on their system. Respond appropriately.',
    expectedProtocol: ['acknowledge query', 'confirm AIS status', 'provide position manually', 'troubleshoot if needed'],
  },
  {
    id: 18,
    title: '18 A',
    description: 'VTS requires ETA, cargo quantity information and number of crew',
    icon: '',
    difficulty: 'beginner',
    objectives: [],
    initialMessage: 'VTS requests detailed information for MV HORIZON. ETA to pilot station: 0800 UTC. Cargo: 15,000 tons grain. Crew: 22 persons.',
    expectedProtocol: ['acknowledge request', 'provide ETA', 'provide cargo details', 'provide crew number', 'confirm'],
  },
  {
    id: 19,
    title: '19 A',
    description: 'Asking for ship particulars and ETA',
    icon: '',
    difficulty: 'beginner',
    objectives: [],
    initialMessage: 'Port Authority requests ship particulars for MV UNITY. LOA: 180m, Beam: 28m, Draft: 10.5m, ETA: 1400 UTC.',
    expectedProtocol: ['acknowledge request', 'provide dimensions', 'provide draft', 'provide ETA', 'any special requirements'],
  },
  {
    id: 20,
    title: '20 A',
    description: 'Informing VTS about dangerous cargo type and quantity',
    icon: '',
    difficulty: 'intermediate',
    objectives: [],
    initialMessage: 'MV CHEMICAL CARRIER is carrying 5,000 tons of Class 3 flammable liquids (UN 1230). Inform VTS of dangerous cargo.',
    expectedProtocol: ['call VTS', 'vessel identification', 'declare dangerous cargo', 'provide UN number', 'provide quantity', 'confirm safety measures'],
  },
  {
    id: 21,
    title: '21 A',
    description: 'Approaching port',
    icon: '',
    difficulty: 'beginner',
    objectives: [],
    initialMessage: 'MV LIBERTY is 5 nautical miles from port entrance. Contact Port Control for approach instructions.',
    expectedProtocol: ['call port control', 'vessel identification', 'distance from port', 'request approach instructions', 'confirm'],
  },
  {
    id: 22,
    title: '22 A',
    description: 'Vessel at anchor, preparing to get underway',
    icon: '',
    difficulty: 'beginner',
    objectives: [],
    initialMessage: 'MV PROSPERITY at Anchorage B-3 is preparing to weigh anchor and proceed to pilot station. Contact VTS.',
    expectedProtocol: ['call VTS', 'vessel identification', 'current position', 'preparing to weigh anchor', 'intended movement'],
  },
  {
    id: 23,
    title: '23 A',
    description: 'Entering the VTS area, underway to anchor for bunkering',
    icon: '',
    difficulty: 'intermediate',
    objectives: [],
    initialMessage: 'MV FORTUNE entering VTS area, requires anchorage for bunkering operations. Contact VTS for anchorage assignment.',
    expectedProtocol: ['call VTS', 'vessel identification', 'position', 'request anchorage for bunkering', 'duration estimate'],
  },
  {
    id: 24,
    title: '24 A',
    description: 'Sending the passage plan',
    icon: '',
    difficulty: 'intermediate',
    objectives: [],
    initialMessage: "MV NAVIGATOR must submit passage plan to VTS. Route: Pilot Station - Waypoint A (52°10'N 004°20'E) - Waypoint B (52°05'N 004°15'E) - Berth 12.",
    expectedProtocol: ['call VTS', 'vessel identification', 'provide waypoints', 'provide route', 'request approval'],
  },
  {
    id: 25,
    title: '25 A',
    description: 'Permission to start bunkering operations',
    icon: '',
    difficulty: 'intermediate',
    objectives: [],
    initialMessage: 'MV ENERGY at Anchorage C-5. Bunker barge alongside. Request permission to start bunkering 800 tons fuel oil.',
    expectedProtocol: ['call VTS', 'vessel identification', 'anchorage position', 'request bunkering permission', 'quantity and type', 'safety confirmation'],
  },
  {
    id: 26,
    title: '26 A',
    description: 'Carriage of dangerous goods',
    icon: '',
    difficulty: 'intermediate',
    objectives: [],
    initialMessage: 'MV HAZMAT TRADER carrying dangerous goods: 2,000 tons Class 2.1 (UN 1965), 1,500 tons Class 8 (UN 1789). Report to VTS.',
    expectedProtocol: ['call VTS', 'vessel identification', 'declare dangerous goods', 'provide classes and UN numbers', 'provide quantities', 'confirm documentation'],
  },
  {
    id: 27,
    title: '27 A',
    description: 'Arrival of pilot and preparations for berthing',
    icon: '',
    difficulty: 'beginner',
    objectives: [],
    initialMessage: 'Pilot has boarded MV CONTINENTAL. Preparing for berthing at Terminal 5. Contact VTS with status.',
    expectedProtocol: ['call VTS', 'vessel identification', 'pilot onboard', 'destination berth', 'ready to proceed'],
  },
  {
    id: 28,
    title: '28 A',
    description: 'Pilot transfer arrangements',
    icon: '',
    difficulty: 'intermediate',
    objectives: [],
    initialMessage: 'MV EMPRESS approaching pilot boarding area. Speed: 6 knots. Pilot ladder rigged on starboard side, 2 meters above water. Contact pilot boat.',
    expectedProtocol: ['call pilot boat', 'vessel identification', 'confirm position', 'boarding arrangements', 'confirm safety measures'],
  },
  {
    id: 29,
    title: '29 A',
    description: 'VTS conveys pilot boarding information',
    icon: '',
    difficulty: 'beginner',
    objectives: [],
    initialMessage: "VTS informs you that pilot will board at position 51°55'N 003°25'E at 1530 UTC. Acknowledge and confirm.",
    expectedProtocol: ['acknowledge information', 'read back position', 'read back time', 'confirm preparations'],
  },
  {
    id: 30,
    title: '30 A',
    description: 'Tugboat report',
    icon: '',
    difficulty: 'intermediate',
    objectives: [],
    initialMessage: 'Tugboat ATLAS completed berthing assistance for MV GLOBAL at Berth 9. Now returning to standby position. Report to VTS.',
    expectedProtocol: ['call VTS', 'tugboat identification', 'operation completed', 'assisted vessel', 'current status'],
  },
];

export const bScenarios = [
  {
    id: 31,
    title: '31 B',
    description: 'Checking a reported spillage',
    icon: '',
    difficulty: 'advanced',
    objectives: [],
    initialMessage: 'VTS reports possible oil spillage at position 52°20\'N 004°10\'E. MV OBSERVER is nearby. Investigate and report findings.',
    expectedProtocol: ['acknowledge request', 'proceed to investigate', 'report observations', 'provide details', 'await instructions']
  },
  {
    id: 32,
    title: '32 B',
    description: 'Vessel must reduce excessive speed',
    icon: '',
    difficulty: 'advanced',
    objectives: [],
    initialMessage: 'VTS instructs MV RAPID to reduce speed from 15 knots to 8 knots due to traffic conditions. Acknowledge and comply.',
    expectedProtocol: ['acknowledge instruction', 'confirm speed reduction', 'report new speed', 'comply immediately']
  },
  {
    id: 33,
    title: '33 B',
    description: 'Vessel navigating in a narrow waterway',
    icon: '',
    difficulty: 'advanced',
    objectives: [],
    initialMessage: 'MV CHANNEL MASTER entering narrow waterway. Width: 200 meters. Vessel beam: 32 meters. Report to VTS and request traffic information.',
    expectedProtocol: ['call VTS', 'vessel identification', 'entering narrow waterway', 'request traffic information', 'confirm safe passage']
  },
  {
    id: 34,
    title: '34 B',
    description: 'Vessel adrift due to unstable weather forecast',
    icon: '',
    difficulty: 'advanced',
    objectives: [],
    initialMessage: 'MV STORM RIDER experiencing engine failure in severe weather. Position: 53°15\'N 005°30\'E. Vessel adrift. Contact VTS urgently.',
    expectedProtocol: ['call VTS urgently', 'vessel identification', 'report adrift', 'position', 'weather conditions', 'request assistance']
  },
  {
    id: 35,
    title: '35 B',
    description: 'Strange object in the fairway',
    icon: '',
    difficulty: 'advanced',
    objectives: [],
    initialMessage: 'MV VIGILANT spotted large unidentified floating object in fairway at position 51°45\'N 003°55\'E. Report to VTS.',
    expectedProtocol: ['call VTS', 'vessel identification', 'report hazard', 'position', 'description', 'navigation status']
  },
  {
    id: 36,
    title: '36 B',
    description: 'Getting underway without having received clearance',
    icon: '',
    difficulty: 'advanced',
    objectives: [],
    initialMessage: 'VTS notices MV HASTY has left berth without departure clearance. You are the vessel. Respond to VTS inquiry.',
    expectedProtocol: ['acknowledge call', 'apologize', 'provide explanation', 'current position', 'request clearance']
  },
  {
    id: 37,
    title: '37 B',
    description: 'Entering the TSS in a wrong way',
    icon: '',
    difficulty: 'advanced',
    objectives: [],
    initialMessage: 'VTS alerts MV CONFUSED that you are entering TSS against traffic flow. Current heading 180°, should be 000°. Respond and correct.',
    expectedProtocol: ['acknowledge alert', 'confirm error', 'state corrective action', 'provide new course', 'confirm compliance']
  },
  {
    id: 38,
    title: '38 B',
    description: 'Approaching harbour with reduced visibility',
    icon: '',
    difficulty: 'advanced',
    objectives: [],
    initialMessage: 'MV FOGBOUND approaching harbor entrance. Visibility reduced to 0.5 nautical miles due to fog. Report to Port Control.',
    expectedProtocol: ['call port control', 'vessel identification', 'position', 'report reduced visibility', 'sound signals', 'request instructions']
  },
  {
    id: 39,
    title: '39 B',
    description: 'Vessel not under command',
    icon: '',
    difficulty: 'advanced',
    objectives: [],
    initialMessage: 'MV DISABLED has complete steering failure at position 52°30\'N 004°45\'E. Unable to maneuver. Declare NUC status to VTS.',
    expectedProtocol: ['call VTS urgently', 'vessel identification', 'declare NUC', 'position', 'nature of problem', 'request assistance']
  },
  {
    id: 40,
    title: '40 B',
    description: 'Drifting into territorial waters',
    icon: '',
    difficulty: 'advanced',
    objectives: [],
    initialMessage: 'MV CURRENT has lost propulsion and is drifting toward territorial waters. Position: 51°50\'N 002°15\'E. Drift rate: 2 knots. Contact authorities.',
    expectedProtocol: ['call authorities', 'vessel identification', 'report drifting', 'position and drift rate', 'request assistance', 'provide vessel details']
  },
  {
    id: 41,
    title: '41 B',
    description: 'Navigation in icy Arctic Navarea with icebreaker assistance',
    icon: '',
    difficulty: 'advanced',
    objectives: [],
    initialMessage: 'MV POLAR STAR entering Arctic NAVAREA. Ice concentration: 7/10. Request icebreaker assistance from Arctic Control.',
    expectedProtocol: ['call Arctic control', 'vessel identification', 'position', 'ice conditions', 'request icebreaker', 'vessel ice class']
  },
  {
    id: 42,
    title: '42 B',
    description: 'Operating with an icebreaker while in transit through the ice',
    icon: '',
    difficulty: 'advanced',
    objectives: [],
    initialMessage: 'MV FROZEN following icebreaker TITAN through ice field. Icebreaker requests you maintain 3 cable lengths distance. Acknowledge.',
    expectedProtocol: ['acknowledge icebreaker', 'vessel identification', 'confirm distance', 'maintain communication', 'follow instructions']
  },
  {
    id: 43,
    title: '43 B',
    description: 'Improper securing of timber deck cargo',
    icon: '',
    difficulty: 'advanced',
    objectives: [],
    initialMessage: 'VTS reports MV TIMBER has shifting deck cargo observed from shore. Heavy weather expected. Respond to VTS concern.',
    expectedProtocol: ['acknowledge report', 'vessel identification', 'assess situation', 'report cargo status', 'corrective action', 'request shelter if needed']
}];